---
- name: Configure Oracle Linux 7.1 with WebLogic 12c R2 domain
  hosts: localhost 
  become: true
  vars_files:
    # User defined variables for infrastructure
    - infra-vars.yml
    # Common properties. You may not delete this
    - wls-vars.yml
    # Infrastructure passwords
    - secrets.yml
  roles:
    - role: linux-wls
      when: nm_status != "running"
    - role: linux-jdk
      when: nm_status != "running"
    - role: fmw-software
      become: true
      become_user: '{{ oracle_user }}'
      when: nm_status != "running"
    - role: fmw-domain
      become_user: '{{ oracle_user }}'
      when: nm_status != "running"
    - role: node-manager
      when: nm_status != "running"
    - role: start-admin-server
      become_user: '{{ oracle_user }}'
      when: nm_status != "running"
    - role: fmw-managed-server
      become_user: '{{ oracle_user }}'
      when: nm_status != "running"
    - role: fmw-odi-server
      become_user: '{{ oracle_user }}'
      when: nm_status != "running"
  pre_tasks:
    # ==> Fix hosts file. Remove hostname from local loop. A workaround for
    # remove hostname to local loop
    #- name: fix host file 127.0.0.1 entry
    #  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4' owner=root group=root mode=0644

   - name: populate service facts
     service_facts:
   
   - debug:
       var: ansible_facts.services["nodemanager.service"].state

   - set_fact:
       nm_status: "{{ansible_facts.services['nodemanager.service'].state if ansible_facts.services['nodemanager.service'] is defined else 'null' }}"
     #when: ansible_facts.services['nodemanager.service'] is defined

