################################################################################
# ==> tasks for linux-jdk Role that installs JDK in an Oracle Linux 7 system
################################################################################

# ==> Install JDK
#- name: Copy jdk archive to host
#  copy: src={{ jdk_installation_archive }} dest=~/{{ jdk_installation_archive }}
#  args:
#    force: no
- name: Download JDK
  get_url:
    url: "{{jdk_url}}"
    dest: "~/{{ jdk_installation_archive }}"
    url_username: "{{ artifactory_user }}"
    url_password: "{{ artifactory_password }}"
    validate_certs: no
  retries: '{{ get_url_vars.retries }}'
  delay: '{{ get_url_vars.retries }}'
  register: get_url_result
  until: get_url_result is succeeded
- name: Extract JDK archive
  command: 'tar -xf ~/{{ jdk_installation_archive }} -C {{ oracle_base }}'
  args:
    creates: "{{ jdk_folder }}"
- name: Change ownership of jdk folder
  file: path="{{ jdk_folder }}" owner={{ oracle_user }} group={{ oracle_group }} recurse=yes
- name: Change entropy device for java
  command: "sed -i.bak 's/\\/dev\\/random/\\/dev\\/.\\/urandom/' {{ jdk_folder }}/jre/lib/security/java.security"
- name: Add JAVA_HOME environment variariables in bashrc
  lineinfile: dest='/home/{{ oracle_user }}/.bashrc' line='export JAVA_HOME={{ jdk_folder }}'
- name: Add Java bin folder to path in bashrc
  lineinfile: dest='/home/{{ oracle_user }}/.bashrc' line='export PATH=$PATH:$JAVA_HOME/bin'
